# Generated by Django 5.1.6 on 2025-02-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmember',
            name='is_active',
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
